spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://PDB-IO-LCSQL-1;database=JdbcTest;
    password: Passw0rd
    username: sa

  #    hikari:
#      maximumPoolSize: 300
  jpa:
     show-sql: false
#server:
#  tomcat:
#    threads:
#      max: 40