version: '3.7'

services:
  influxdb:
    build: './config/influxdb'
#    image: influxdb:1.8.4
    container_name: monitoring_influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=jmeter
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  chronograf:
    image: chronograf:1.8
    container_name: monitoring_chronograf
    ports:
      - 8888:8888
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
  grafana:
    build: './config/grafana'
    container_name: monitoring_grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    build: './config/prometheus'
    container_name: monitoring_prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-storage:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
  postgresql_for_jdbc:
    image: postgres:12
    container_name: postgres_jdbc
    restart: on-failure
    ports:
      - 5433:5432
    expose:
      - '5433'
    volumes:
      - pg-jdbc-storage:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=jdbc_vs_r2dbc
  postgresql_for_r2dbc:
    image: postgres:12
    container_name: postgres_r2dbc
    restart: on-failure
    ports:
      - 5434:5432
    expose:
      - '5434'
    volumes:
      - pg-r2dbc-storage:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=jdbc_vs_r2dbc

networks:
  monitoring:

volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
  pg-r2dbc-storage:
  pg-jdbc-storage:
  prometheus-storage: