version: '3.7'

services:
  grafana:
    build: './config/grafana'
    container_name: monitoring_grafana
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    build: './config/prometheus'
    container_name: monitoring_prometheus
    ports:
      - 9090:9090
    volumes:
      - ./volumes/prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
  influxdb:
    build: './config/influxdb'
    container_name: monitoring_influxdb
    environment:
      - INFLUXDB_DB=jmeter
    ports:
      - 8086:8086
      - 8088:8088
      - 2003:2003
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    networks:
      monitoring:
        aliases:
          - influxdb

networks:
  monitoring: