version: '3.7'

services:
  grafana:
    build: './config/grafana'
    container_name: monitoring_grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    build: './config/prometheus'
    container_name: monitoring_prometheus
    ports:
      - 9090:9090
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring: