version: '3.7'

services:
  influxdb:
    build: './config/influxdb'
    container_name: monitoring_influxdb
    environment:
      - INFLUXDB_DB=jmeter
    ports:
      - 8086:8086
      - 2003:2003
#    volumes:
#      - ./volumes/influxdb:/var/lib/influxdb
    networks:
      monitoring:
        aliases:
          - influxdb
  grafana:
    build: './config/grafana'
    container_name: monitoring_grafana
    ports:
      - 3000:3000
#    volumes:
#      - ./volumes/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    build: './config/prometheus'
    container_name: monitoring_prometheus
    ports:
      - 9090:9090
#    volumes:
#      - ./volumes/prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
  postgresql_for_jdbc:
    image: postgres:12
    container_name: postgres
    restart: on-failure
    ports:
      - 5433:5432
    expose:
      - '5433'
#    volumes:
#      - ./volume/pg_jdbc:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=jdbc_vs_r2dbc
  postgresql_for_r2dbc:
    image: postgres:12
    container_name: postgres
    restart: on-failure
    ports:
      - 5434:5432
    expose:
      - '5434'
#    volumes:
#      - ./volume/pg_jdbc:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=jdbc_vs_r2dbc

networks:
  monitoring: