spring:
  liquibase:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://PDB-IO-LCSQL-1;database=R2dbcTest;
    user: sa
    password: Passw0rd
  r2dbc:
    url: r2dbc:sqlserver://PDB-IO-LCSQL-1/R2dbcTest
    username: sa
    password: Passw0rd