{
 "title": "Prometheus_metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Live Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\njvm_threads_live_threads{instance=\"host.docker.internal:8081\", job=\"jdbc_monitoring\"}",
     "legendFormat": "JDBC"
    },
    {
     "expr": "\r\njvm_threads_live_threads{instance=\"host.docker.internal:8082\", job=\"r2dbc_monitoring\"}",
     "legendFormat": "R2DBC"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"host.docker.internal:8081\", job=\"jdbc_monitoring\"}\r",
     "legendFormat": "JDBC"
    },
    {
     "expr": "process_cpu_usage{instance=\"host.docker.internal:8082\", job=\"r2dbc_monitoring\"}\r",
     "legendFormat": "R2DBC"
    }
   ]
  },
  {
   "title": "Heap. G1 Eden Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"G1 Eden Space\", instance=\"host.docker.internal:8081\", job=\"jdbc_monitoring\"}\r",
     "legendFormat": "JDBC"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"G1 Eden Space\", instance=\"host.docker.internal:8082\", job=\"r2dbc_monitoring\"}\r",
     "legendFormat": "R2DBC"
    }
   ]
  },
  {
   "title": "G1 Old Gen",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"G1 Old Gen\", instance=\"host.docker.internal:8081\", job=\"jdbc_monitoring\"}\r",
     "legendFormat": "JDBC"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"G1 Old Gen\", instance=\"host.docker.internal:8082\", job=\"r2dbc_monitoring\"}\r",
     "legendFormat": "R2DBC"
    }
   ]
  }
 ]
}